<a href="https://colab.research.google.com/github/mehdi-abbasi/ML_Course_ResearhStudy_prj/blob/main/ML_paper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

In [47]:
import io
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [61]:
df = pd.read_csv(io.BytesIO(uploaded['dataset.csv']))
df

Flow ID  ...   Label
0         192.168.10.14-209.48.71.168-49459-80-6  ...  BENIGN
1         192.168.10.3-192.168.10.17-389-49453-6  ...  BENIGN
2          192.168.10.3-192.168.10.17-88-46124-6  ...  BENIGN
3         192.168.10.3-192.168.10.17-389-49454-6  ...  BENIGN
4          192.168.10.3-192.168.10.17-88-46126-6  ...  BENIGN
...                                          ...  ...     ...
692698    192.168.10.3-192.168.10.14-53-51114-17  ...  BENIGN
692699    192.168.10.3-192.168.10.16-53-24054-17  ...  BENIGN
692700  192.168.10.51-23.208.163.130-58030-443-6  ...  BENIGN
692701    192.168.10.3-192.168.10.14-53-51694-17  ...  BENIGN
692702    192.168.10.3-192.168.10.14-53-57949-17  ...  BENIGN

[692703 rows x 85 columns]

In [62]:
df = pd.read_csv(io.BytesIO(uploaded['dataset.csv']))
print(df.isnull().sum().sum())
df.replace([np.inf, - np.inf], np.nan, inplace = True)
print(df.isnull().sum().sum())
df = df.dropna() 
df = df.reset_index(drop=True)
X = df._get_numeric_data().values
Y = df[' Label']
print(df.isnull().sum().sum())
print('List of labels:',list(set(Y)))

1008
2594
0
List of labels: ['DoS slowloris', 'BENIGN', 'DoS Hulk', 'DoS GoldenEye', 'Heartbleed', 'DoS Slowhttptest']


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,  test_size=0.3,random_state=1)

In [19]:
mlp1 = MLPClassifier(random_state=5,hidden_layer_sizes=(100,))
mlp1.fit(X_train, y_train)

MLPClassifier(random_state=5)

In [22]:
mlp1.score(X_test, y_test)

0.7547993944711747

In [31]:
mlp2 = MLPClassifier(random_state=5,hidden_layer_sizes=(100,100))
mlp2.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(100, 100), random_state=5)

In [32]:
mlp2.score(X_test, y_test)

0.6368610851307962

In [29]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)

RandomForestClassifier()

In [30]:
rf.score(X_test, y_test)

0.9993829005602106

In [66]:
mlp1_pred = mlp1.predict(X_test)
mlp2_pred = mlp2.predict(X_test)
rf_pred = rf.predict(X_test)
print('confusion_matrix_MLP1')
print(confusion_matrix(mlp1_pred,y_pred))
print('-----------------------------')
print('confusion_matrix_MLP2')
print(confusion_matrix(mlp2_pred,y_pred))
print('-----------------------------')
print('confusion_matrix_RF')
print(confusion_matrix(rf_pred,y_pred))

confusion_matrix_MLP1
[[182091      0      0      0      0]
 [     0      6      0      0      0]
 [     0      0  25019      0      0]
 [     0      0      0    105      0]
 [     0      0      0      0    201]]
-----------------------------
confusion_matrix_MLP2
[[182091      6  25019    105    201]
 [     0      0      0      0      0]
 [     0      0      0      0      0]
 [     0      0      0      0      0]
 [     0      0      0      0      0]]
-----------------------------
confusion_matrix_RF
[[131694      0    216     18    162      0]
 [  3049      6     27      0      0      0]
 [ 44127      0  24776      4      0      0]
 [  1586      0      0     83      0      0]
 [  1631      0      0      0     39      0]
 [     4      0      0      0      0      0]]
